### ISSUE TITLE
cargo test --workspace fails in my local dev environment

### ISSUE THREAD

**Issue by zancas** [zingolabs/zecwalletlitelib#30]
I see this commit locally:   b13c2a22b0ab730308e90437ea53dd902029d6b1

**Comment by zancas** [comment]
This failure is due to `keygen.sh` not running before the `test_server` HTTPS tests.   The relevant tests need to ensure the existence of the cert-key prior to running.

**Comment by AloeareV** [comment]
I've found a few different options for this.. Among them, https://github.com/la10736/rstest and https://github.com/mindsbackyard/galvanic-test

`rstest` looks the most minimal of the options I've looked at, so far.

**Comment by AloeareV** [comment]
Another (more involved) option is to use our own test harness.

**Comment by AloeareV** [comment]
... Or I could just put it inside of `create_test_server()`. _Duh._

**Comment by zancas** [comment]
I say throw it in `create_test_server` and throw the file in the test-specific temp-dir.   I'm a huge fan of ALL test state being in a test-specific, easily found location.
