### ISSUE TITLE
Let's integrate keygen.sh with the appropriate (test_server-HTTPS) tests.

### ISSUE THREAD

**Issue by zancas** [zingolabs/zecwalletlitelib#32]

**Comment by zancas** [comment]
I lost a little time trying to figure out why test_server tests started failing when I split into a `git worktree`

**Comment by AloeareV** [comment]
Agree. I spent about 10-15 minutes looking into figuring out an idiomatic way to do this, when I first added the script. Will look more into this at some point later today, unless you beat me to it.

**Comment by AloeareV** [comment]
Duplicate of #30
